FROM openjdk:8
EXPOSE 8761
VOLUME /tmp
ADD target/eureka-service-1.0-SNAPSHOT.jar eureka-service.jar
RUN bash -c 'touch /eureka-service.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar", "/eureka-service.jar"]