version: '3.7'
services:
    eureka-service:
      build: ./eureka-service
      ports:
        - "8761:8761"
      expose:
        - "8761"
      container_name: eureka-service
      environment:
        eureka.instance.preferIpAddress: 'true'
        spring.boot.admin.client.prefer-ip: 'true'
        spring.boot.admin.client.url: http://spring-boot-admin-service:8762
  
    personnes-service:
      build: ./personnes-service
      ports:
        - 8080:8080
      expose:
        - "8080"
      volumes:
        - /tmp
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
        eureka.instance.preferIpAddress: 'true'
        spring.boot.admin.client.prefer-ip: 'true'
        spring.boot.admin.client.url: http://spring-boot-admin-service:8762
      container_name: personnes-service
      depends_on:
        - mongodb

    mongodb:
      image: mongo
      restart: always
      ports: 
        - 27017:27017
      volumes:
        - ./personnes-service/init_mongo_db.js:/docker-entrypoint-initdb.d/init.js
        - db-data-mongodb:/data/db
      container_name: personnes-service-mongodb
    
    taches-service:
      build: ./taches-service
      ports:
        - 8180:8180
      expose:
        - "8180"
      volumes:
        - /tmp
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
        eureka.instance.preferIpAddress: 'true'
        spring.boot.admin.client.prefer-ip: 'true'
        spring.boot.admin.client.url: http://spring-boot-admin-service:8762
      container_name: taches-service
      depends_on:
        - pgdb

    rabbitmq-service:
      image: rabbitmq
      ports:
        - 5672:5672
      container_name: rabbitmq-service
    
    pgdb:
      image: postgres
      restart: always
      ports:
        - 5432:5432
      volumes:
        - ./taches-service/init_postgres_db.sql:/docker-entrypoint-initdb.d/init.sql
        - db-data-postgres:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWRD: motdepasse
      container_name: taches-service-postgres
    
    oauth-service:
      build: ./oauth-service
      ports:
        - 9191:9191
      expose:
        - "9191"
      volumes:
        - /tmp
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
        eureka.instance.preferIpAddress: 'true'
        spring.boot.admin.client.prefer-ip: 'true'
        spring.boot.admin.client.url: http://spring-boot-admin-service:8762
      container_name: oauth-service

    gateway-service:
      build: ./gateway-service
      ports:
        - 9291:9291
      expose:
        - "9291"
      volumes:
        - /tmp
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
        eureka.instance.preferIpAddress: 'true'
      container_name: gateway-service

    monitor-service:
      build: ./monitor-service
      ports:
        - 9903:9903
      expose:
        - "9903"
      volumes:
        - /tmp
      environment: 
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
        eureka.instance.preferIpAddress: 'true'
        spring.boot.admin.client.prefer-ip: 'true'
        spring.boot.admin.client.url: http://spring-boot-admin-service:8762
      container_name: monitor-service
    
    spring-boot-admin-service:
      build: ./spring-boot-admin-service
      ports:
        - 8762:8762
      expose:
        - "8762"
      volumes:
        - /tmp
      environment: 
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
        eureka.instance.preferIpAddress: 'true'
        spring.boot.admin.client.prefer-ip: 'true'
      container_name: spring-boot-admin-service

    zipkin-service:
      build: ./zipkin-service
      ports:
        - 9411:9411
      expose:
        - "9411"
      volumes:
        - /tmp
      environment: 
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
        eureka.instance.preferIpAddress: 'true'
        spring.boot.admin.client.prefer-ip: 'true'
        spring.boot.admin.client.url: http://spring-boot-admin-service:8762
      container_name: zipkin-service

volumes:
  db-data-postgres:
    driver: local
  db-data-mongodb:
    driver: local
  