FROM openjdk:8
EXPOSE 9291
VOLUME /tmp
ADD gateway-service-1.0-SNAPSHOT.jar gateway-service.jar
RUN bash -c 'touch /gateway-service.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar", "/gateway-service.jar"]